version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: pos
      POSTGRES_PASSWORD: pos
      POSTGRES_DB: pos
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:v1.15.3
    ports:
      - "6333:6333"
